/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: rpapagna <rpapagna@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/04/07 22:34:38 by rpapagna          #+#    #+#             */
/*   Updated: 2019/05/03 06:24:09 by rpapagna         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/ft_printf.h"
#include <stdio.h>

/*
**checks for working libc printf funcitons
*/

int		main(void)
{
	int			a1;
	int			a2;
	int			b1;
	int			b2;
	int			c1;
	int			c2;
	int			n1;
	int			n2;
	char		d;
	char		e;
	char		f;
	char		*s1;
	char		*s2;
	char		**str;
	double		x;
	long double	y;

	ft_printf("these are tests for my own printf vs libc printf\n\n");
	a1 = 1;
	a2 = 2;
	b1 = 10;
	b2 = -20;
	c1 = 100;
	c2 = -200;
	d = 'A';
	e = 'B';
	f = 'C';
	s1 = "hi";
	s2 = "hello";
	x = 1.1;
	y = 2.44444445;
	d = 1;
	ft_printf("%f\n", 3.9999999);
	printf("%f\n", 3.9999999);
	printf("{%10R}");
	return (0);
}
/*
**	ft_printf("my printf say    :");
**	ft_printf("{%*d}\n", -5, 42);
**	ft_printf("libc printf says :");
**	printf("{%*d}\n", -5, 42);
**	ft_printf("my printf say    :");
**	ft_printf("{%*3d}\n", 0, 0);
**	ft_printf("libc printf says :");
**	printf("{%*3d}\n", 0, 0);
**	ft_printf("my printf say    :");
**	ft_printf("{%3*d}.\n", 2, 16);
**	ft_printf("libc printf says :");
**	printf("{%3*d}.\n\n", 2, 16);
**	ft_printf("my printf say    :");
**	ft_printf("{%1*d}.\n", 17, 98765);
**	ft_printf("libc printf says :");
**	printf("{%1*d}.\n\n", 17, 98765);
**	ft_printf("my printf say    :");
**	ft_printf("{%15*d}.\n", 17, 98765);
**	ft_printf("libc printf says :");
**	printf("{%15*d}.\n\n", 17, 98765);
**	ft_printf("my printf say    :");
**	ft_printf("{%5p}\n", 0);
**	ft_printf("libc printf says :");
**	printf("{%5p}\n", 0);
**	ft_printf("my printf say    :");
**	ft_printf("%.5p, %.0p\n", 0, 0);
**	ft_printf("libc printf says :");
**	printf("%.5p, %.0p\n", 0, 0);
**	ft_printf("my printf say    :");
**	ft_printf("%.0p, %.p\n", 0, 0);
**	ft_printf("libc printf says :");
**	printf("%.0p, %.p\n", 0, 0);
**	ft_printf("my printf say    :");
**	ft_printf("%9.2p\n", 1234);
**	ft_printf("libc printf says :");
**	printf("%9.2p\n", 1234);
**	ft_printf("my printf say    :");
**	ft_printf("%2.9p\n", 1234);
**	ft_printf("libc printf says :");
**	printf("%2.9p\n", 1234);
**	ft_printf("%Lf\n", y);
**	printf("%Lf\n", y);
**	y++;
**	ft_printf("%Lf\n", y);
**	printf("%Lf\n", y);
**	ft_printf("my printf say    :");
**	ft_printf("% o|%+o\n", 42, 42);
**	ft_printf("libc printf says :");
**	printf("% o|%+o\n", 42, 42);
**	ft_printf("my printf say    :");
**	ft_printf("%.5p, %.0p\n", 0, 0);
**	ft_printf("libc printf says :");
**	printf("%.5p, %.0p\n", 0, 0);
**	ft_printf("my printf say    :");
**	ft_printf("%.0p, %.p\n", 0, 0);
**	ft_printf("libc printf says :");
**	printf("%.0p, %.p\n", 0, 0);
**	ft_printf("my printf say    :");
**	ft_printf("%9.2p\n", 1234);
**	ft_printf("libc printf says :");
**	printf("%9.2p\n", 1234);
**	ft_printf("my printf say    :");
**	ft_printf("%2.9p\n", 1234);
**	ft_printf("libc printf says :");
**	printf("%2.9p\n", 1234);
**	   printf("no prc     : %#.0f\n", 1.0);
**	ft_printf("no prc  ft : %#.0f\n", 1.0);
**	   printf("no prc     : %.0f\n", 1.0);
**	ft_printf("no prc  ft : %.0f\n", 1.0);
**	   printf("no prc -   : %-#5.0f\n", 1.0);
**	ft_printf("no prc -ft : %-#5.0f\n", 1.0);
**	   printf("no prc -   : %-5.0f\n", 1.0);
**	ft_printf("no prc -ft : %-5.0f\n", 1.0);
**	   printf(".0         : %.0f\n", 0);
**	ft_printf(".0      ft : %.0f\n", 0);
**	   printf(".1         : %.1f\n", 0);
**	ft_printf(".1      ft : %.1f\n", 0);
**	   printf(".2         : %.2f\n", 0);
**	ft_printf(".2      ft : %.2f\n", 0);
**	   printf(".3         : %.3f\n", 0);
**	ft_printf(".3      ft : %.3f\n", 0);
**	   printf(".4         : %.4f\n", 0);
**	ft_printf(".4      ft : %.4f\n", 0);
**	   printf(".5         : %.5f\n", 0);
**	ft_printf(".5      ft : %.5f\n", 0);
**	   printf(".6         : %.6f\n", 0);
**	ft_printf(".6      ft : %.6f\n", 0);
**	   printf(".7         : %.7f\n", 0);
**	ft_printf(".7      ft : %.7f\n", 0);
**	   printf(".8         : %.8f\n", 0);
**	ft_printf(".8      ft : %.8f\n", 0);
**	   printf(".9         : %.9f\n", 0);
**	ft_printf(".9      ft : %.9f\n", 0);
**	   printf("lib  no flag      :\"%f\"\n", x);
**	ft_printf("ft_  no flag      :\"%f\"\n\n", x);
**	   printf("lib  .8           :\"%.8f\"\n", y);
**	ft_printf("ft_  .8           :\"%.8f\"\n\n", y);
**	   printf("lib  20w          :\"%20f\"\n", x);
**	ft_printf("ft_  20w          :\"%20f\"\n\n", x);
**	   printf("lib  10w          :\"%10f\"\n", y);
**	ft_printf("ft_  10w          :\"%10f\"\n\n", y);
**	ft_printf("%-50.15b\n %20b", c1, 255);
**	mod.prcsn = -1;
**	str = num_string_modld(y, mod);
**	mod.prcsn = 6;
**	str = num_string_modld(y, mod);
**	mod.prcsn = 7;
**	str = num_string_modld(y, mod);
**	mod.prcsn = 8;
**	str = num_string_modld(y, mod);
**	mod.prcsn = 9;
**	str = num_string_modld(y, mod);
**
**  printf(".0     : %.0Lf\n", y);
**  printf(".1     : %.1Lf\n", y);
**  printf(".2     : %.2Lf\n", y);
**  printf(".3     : %.3Lf\n", y);
**	printf(".4     : %.4Lf\n", y);
**	printf(".5     : %.5Lf\n", y);
**
**	   printf("  -p noflags :\"%p\"\n", &s1);
**	ft_printf("ft-p noflags :\"%p\"\n\n", &s1);
**	   printf("  -p #       :\"%#p\"\n", &s1);
**	ft_printf("ft-p #       :\"%#p\"\n\n", &s1);
**	   printf("  -p +       :\"%+p\"\n", &s1);
**	ft_printf("ft-p +       :\"%+p\"\n\n", &s1);
**	   printf("  -p NULL nf :\"%p\"\n", NULL);
**	ft_printf("ft-p NULL nf :\"%p\"\n\n", NULL);
**	   printf("  -p sp      :\"% p\"\n", &d);
**	ft_printf("ft-p sp      :\"% p\"\n\n", &d);
**	   printf("  -p - 20w   :\"%-20p\"\n", &d);
**	ft_printf("ft-p - 20w   :\"%-20p\"\n\n", &d);
**	   printf("  -p - 020w  :\"%-020p\"\n", &d);
**	ft_printf("ft-p - 020w  :\"%-020p\"\n\n", &d);
**	   printf("  -p .0      :\"%.0p\"\n", &d);
**	ft_printf("ft-p .0      :\"%.0p\"\n\n", &d);
**	   printf("  -p .noprec :\"%.p\"\n", &d);
**	ft_printf("ft-p .noprec :\"%.p\"\n\n", &d);
**	   printf("  -p 12w     :\"%12p\"\n", &d);
**	ft_printf("ft-p 12w     :\"%12p\"\n\n", &d);
**	   printf("  -p 13w     :\"%13p\"\n", &d);
**	ft_printf("ft-p 13w     :\"%13p\"\n\n", &d);
**	   printf("  -p 14w     :\"%14p\"\n", &d);
**	ft_printf("ft-p 14w     :\"%14p\"\n\n", &d);
**	   printf("  -p 15w     :\"%15p\"\n", &d);
**	ft_printf("ft-p 15w     :\"%15p\"\n\n", &d);
**	   printf("  -p 20w     :\"%20p\"\n", &d);
**	ft_printf("ft-p 20w     :\"%20p\"\n\n", &d);
**	   printf("  -p 012w    :\"%012p\"\n", &d);
**	ft_printf("ft-p 012w    :\"%012p\"\n\n", &d);
**	   printf("  -p 013w    :\"%013p\"\n", &d);
**	ft_printf("ft-p 013w    :\"%013p\"\n\n", &d);
**	   printf("  -p 014w    :\"%014p\"\n", &d);
**	ft_printf("ft-p 014w    :\"%014p\"\n\n", &d);
**	   printf("  -p 015w    :\"%015p\"\n", &d);
**	ft_printf("ft-p 015w    :\"%015p\"\n\n", &d);
**	   printf("  -p 020w    :\"%020p\"\n", &d);
**	ft_printf("ft-p 020w    :\"%020p\"\n\n", &d);
**	   printf("  -p .12     :\"%.12p\"\n", &d);
**	ft_printf("ft-p .12     :\"%.12p\"\n\n", &d);
**	   printf("  -p .13     :\"%.13p\"\n", &c2);
**	ft_printf("ft-p .13     :\"%.13p\"\n\n", &c2);
**	   printf("  -p .14     :\"%.14p\"\n", &d);
**	ft_printf("ft-p .14     :\"%.14p\"\n\n", &d);
**	   printf("  -p .15     :\"%.15p\"\n", &d);
**	ft_printf("ft-p .15     :\"%.15p\"\n\n", &d);
**	   printf("  -p 13.12   :\"%13.12p\"\n", &d);
**	ft_printf("ft-p 13.12   :\"%13.12p\"\n\n", &d);
**	   printf("  -p 13.13   :\"%13.13p\"\n", &c2);
**	ft_printf("ft-p 13.13   :\"%13.13p\"\n\n", &c2);
**	   printf("  -p 13.14   :\"%13.14p\"\n", &d);
**	ft_printf("ft-p 13.14   :\"%13.14p\"\n\n", &d);
**	   printf("  -p 13.15   :\"%13.15p\"\n", &d);
**	ft_printf("ft-p 13.15   :\"%13.15p\"\n\n", &d);
**	   printf("  -p 14.12   :\"%14.12p\"\n", &d);
**	ft_printf("ft-p 14.12   :\"%14.12p\"\n\n", &d);
**	   printf("  -p 14.13   :\"%14.13p\"\n", &c2);
**	ft_printf("ft-p 14.13   :\"%14.13p\"\n\n", &c2);
**	   printf("  -p 14.14   :\"%14.14p\"\n", &d);
**	ft_printf("ft-p 14.14   :\"%14.14p\"\n\n", &d);
**	   printf("  -p 14.15   :\"%14.15p\"\n", &d);
**	ft_printf("ft-p 14.15   :\"%14.15p\"\n\n", &d);
**	   printf("  -p 15.12   :\"%15.12p\"\n", &d);
**	ft_printf("ft-p 15.12   :\"%15.12p\"\n\n", &d);
**	   printf("  -p 15.13   :\"%15.13p\"\n", &c2);
**	ft_printf("ft-p 15.13   :\"%15.13p\"\n\n", &c2);
**	   printf("  -p 15.14   :\"%15.14p\"\n", &d);
**	ft_printf("ft-p 15.14   :\"%15.14p\"\n\n", &d);
**	   printf("  -p 15.15   :\"%15.15p\"\n", &d);
**	ft_printf("ft-p 15.15   :\"%15.15p\"\n\n", &d);
**	printf("#8.5       : \"%#8.5x\"\n", 34);
**	ft_printf("ft#8.5     : \"%#8.5x\"\n\n", 34);
**	printf("#08.5      : \"%#08.5x\"\n", 34);
**	ft_printf("ft#08.5    : \"%#08.5x\"\n\n", 34);
**	printf("#08.3      : \"%#08.3x\"\n", 8375);
**	ft_printf("#08.3      : \"%#08.3x\"\n\n", 8375);
**	printf("532        : \"%x\"\n", 532);
**	ft_printf("ft5        : \"%x\"\n", 532);
**	printf("-674       : \"%x\"\n", -674);
**	ft_printf("ft-4       : \"%x\"\n", -674);
**	printf("-890       : \"%x\"\n", -890);
**	ft_printf("ft-0       : \"%x\"\n", -890);
**	printf("777        : \"%x\"\n", 777);
**	ft_printf("ft7        : \"%x\"\n", 777);
**	printf("888        : \"%x\"\n", 888);
**	ft_printf("ft8        : \"%x\"\n", 888);
**	printf("999        : \"%.0llx\"\n", 9223372036854775808);
**	ft_printf("ft9        : \"%.0llx\"\n", 9223372036854775808);
**	printf("#3 0       : \"%#3x\"\n", 0);
**	ft_printf("ft#3 0     : \"%#3x\"\n\n", 0);
**	printf("#03 0     : \"%#03x\"\n", 0);
**	ft_printf("ft#3 0    : \"%#03x\"\n\n", 0);
**	ft_printf("%lu\n", (unsigned long)32);
**	printf("%lu\n\n", (unsigned long)32);
**	printf(".0        : \"%.x\"\n", 0);
**	ft_printf("ft.0      : \"%.x\"\n\n", 0);
**	printf("5.        : \"%5.x\"\n", 0);
**	ft_printf("ft5.      : \"%5.x\"\n\n", 0);
**	printf("-4         : \"%#x\"\n", -4);
**	ft_printf("ft-        : \"%#x\"\n\n", -4);
**	printf("15         : \"%#x\"\n", 15);
**	ft_printf("ft1        : \"%#x\"\n\n", 15);
**	printf("0          : \"%.0x\"\n", 0);
**	ft_printf("ft0        : \"%.0x\"\n", 0);
**	printf("0          : \"%.X\"\n", 0);
**	ft_printf("ft0        : \"%.X\"\n", 0);
**
**	printf("2    0      : \"%018x\"\n", 2);
**	ft_printf("ft2  0      : \"%018x\"\n", 2);
**	printf("9    0      : \"%010x\"\n", 9);
**	ft_printf("ft9  0      : \"%010x\"\n", 9);
**	printf("8    0      : \"%0.16x\"\n", 8);
**	ft_printf("ft8  0      : \"%0.16x\"\n", 8);
**	printf("7    0      : \"%.16x\"\n", 7);
**	ft_printf("ft7 0       : \"%.16x\"\n", 7);
**	printf("2          : \"%x\"\n", 2);
**	ft_printf("ft2        : \"%x\"\n", 2);
**	printf("9          : \"%x\"\n", 9);
**	ft_printf("ft9        : \"%x\"\n", 9);
**	printf("8          : \"%x\"\n", 8);
**	ft_printf("ft8        : \"%x\"\n", 8);
**	printf("7          : \"%x\"\n", 7);
**	ft_printf("ft7        : \"%x\"\n", 7);
**	printf("1 sp       : \"% x\"\n", 1);
**	ft_printf("ft1 sp     : \"% x\"\n", 1);
**	printf("% -d.%-d.%-d\n% -c.%-c\n\n", a, b , c, d, e);
**	printf("%+ c.%-0 c.%      c", 49, e, 'g');
**	printf("%-+0.c.%-+0c.%-+ 03c.", d, e, f);
**	printf("%-3.6c.%-6.c.%-6.3c.%6.3c.%.3c.%4c.", d, e, f, 'W', 'X', 'Y');
**	printf("%-03c.%-02c.%-01c.",d, e, f);
**	int p = (int)write(1, ".", 1);
**	printf("%d", p);
**	printf("%01c.%1c.%.1c.", d, e, f);
**	printf("%%.%-05%.%+%.%05%.% .5h%.");
**	printf("%#%.");
**	printf("positive:%d, %d, %Ld\n", a1, b1, c1);
**	printf("pos h   :%hd, %hd, %hd\n", a1, b1, c1);
**	printf("pos hh  :%hhd, %hhd, %hhd\n", a1, b1, c1);
**	printf("pos l   :%ld, %ld, %ld\n", a1, b1, c1);
**	printf("pos ll  :%lld, %lld, %lld\n", a1, b1, c1);
**	printf("negative:%d, %d, %Ld\n", a2, b2, c2);
**	printf("neg h   :%hd, %hd\n", a2, b2, c2);
**	printf("neg hh  :%hhd, %hhd, %hhd\n", a2, b2, c2);
**	printf("neg l   :%ld, %ld, %ld\n", a2, b2, c2);
**	printf("neg ll  :%lld, %lld, %lld\n", a2, b2, c2);
**	printf("+ flag p:%+d, %+d, %+d\n", a1, b1, c1);
**	printf("+ flag n:%+d, %+d, %+d\n", a2, b2, c2);
**	printf("sp flag :%      d, % d\n", c1, c2);
**	printf("0 flag  :%000d\n", a1);
**	printf("- flag  :%-d, %-----d\n", b1, b2);
**	int po = printf("...|%c|...\n", '\0');
**	int bo = printf("...|%c|...\n", 0);
**	printf("%d\n", po);
**	printf("%d\n", bo);
**	printf("single flag\n");
**	printf("space	+d:% d\n", n1);
**	printf("space	-d:% d\n", n2);
**	printf("plus	+d:%+d\n", n1);
**	printf("plus	-d:%+d\n", n2);
**	printf("zero	+d:%0d\n", n1);
**	printf("zero	-d:%0d\n", n2);
**	printf("minus	+d:%-d\n", n1);
**	printf("minus	-d:%-d\n", n2);
**	printf("pound	+d:%#d\n", n1);
**	printf("pound	-d:%#d\n\n", n2);
**
**	printf("+ and single flag\n");
**	printf("space +	+d:% +d\n", n1);
**	printf("space +	-d:% +d\n", n2);
**	printf("0 +	+d:%0+d\n", n1);
**	printf("0 +	-d:%0+d\n", n2);
**	printf("- +	+d:%-+d\n", n1);
**	printf("- +	-d:%-+d\n", n2);
**	printf("# +	+d:%#+d\n", n1);
**	printf("# +	-d:%#+d\n\n", n2);
**
**	printf("sapce and single flag\n");
**	printf("0 space	+d:%0 d\n", n1);
**	printf("0 space	-d:%0 d\n", n2);
**	printf("- space	+d:%- d\n", n1);
**	printf("- space	-d:%- d\n", n2);
**	printf("# space	+d:%# d\n", n1);
**	printf("# space	-d:%# d\n\n", n2);
**
**	printf("zero and single flag\n");
**	printf("- 0	+d:%-0d\n", n1);
**	printf("- 0	-d:%-0d\n", n2);
**	printf("# 0	+d:%#0d\n", n1);
**	printf("# 0	-d:%#0d\n\n", n2);
**	pound is useless here
**	printf("minus and single flag\n");
**	printf("# -	+d:%#-d\n", n1);
**	printf("# -	-d:%#-d\n", n2);
**
**	printf("flags with width\n");
**	printf("single flag width 4\n");
**	printf("space	d:% 4d\n", n1);
**	printf("space 6w d:% 6d.\n", 555);
**	printf("space 4w d:% 4d.\n", 555);
**	printf("space 2w d:% 2d.\n\n", 555);
**	printf("nspce 6w d:%6d.\n", 676);
**	printf("nspce 4w d:%4d.\n", 676);
**	printf("nspce 2w d:%2d.\n\n", 676);
**	printf("nspce 6w d:%6d.\n", 76);
**	printf("nspce 4w d:%4d.\n", 76);
**	printf("nspce 2w d:%2d.\n\n", 76);
**	printf("space 6w d:%+ 6d.\n", 555);
**	printf("space 4w d:%+ 4d.\n", 555);
**	printf("space 2w d:%+ 2d.\n\n", 555);
**	printf("nspce 6w d:%+6d.\n", 676);
**	printf("nspce 4w d:%+4d.\n", 676);
**	printf("nspce 2w d:%+2d.\n\n", 676);
**	printf("nspce 6w d:%+6d.\n", 76);
**	printf("nspce 4w d:%+4d.\n", 76);
**	printf("nspce 2w d:%+2d.\n\n", 76);
**	printf("np  6w d:%6.d.\n", 555);
**	printf("4p  8w d:%8.4d.\n", 555);
**	printf("2p  2w d:%2.2d.\n\n", 555);
**	printf("minus    2w d:%-2d.\n", 555);
**	printf("minus +  2w d:%-+2d.\n", 555);
**	printf("minus sp 2w d:%- 2d.\n", 555);
**	printf("minus +5p  2w d:%-+2.5d.\n", 555);
**	printf("minus sp5p 2w d:%- 2.5d.\n", 555);
**	printf("neg minus    2w d:%-2d.\n", -555);
**	printf("neg minus +  2w d:%-+2d.\n", -555);
**	printf("neg minus sp 2w d:%- 2d.\n", -555);
**	printf("neg minus +5p  2w d:%-+2.5d.\n", -555);
**	printf("neg minus sp5p 2w d:%- 2.5d.\n", -555);
**	printf("minus 5w d:%-5d.\n\n", 555);
**	printf("minus 2p d:%-.2d.\n", 666);
**	printf("minus 5p d:%-.5d.\n\n", 666);
**	printf("6p  nw d:%.6d.\n", 676);
**	printf("4p  8w d:%8.4d.\n", 676);
**	printf("2p  2w d:%2.2d.\n\n", 676);
**	printf("6p  nw d:%.6d.\n", 76);
**	printf("4p  8w d:%8.4d.\n", 76);
**	printf("2p  2w d:%2.2d.\n\n", 76);
**	printf("space	d:% 4d\n", n2);
**	printf("plus	d:%+4d\n", n1);
**	printf("plus	d:%+4d\n", n2);
**	printf("zero	d:%04d\n", n1);
**	printf("zero	d:%04d\n", n2);
**	printf("minus	d:%-4d\n", n1);
**	printf("minus	d:%-4d\n\n", n2);
**
**	printf("+ and single flag width 4\n");
**	printf("space +	d:% +4d\n", n1);
**	printf("space +	d:% +4d\n", n2);
**	printf("0 +	d:%0+4d\n", n1);
**	printf("0 +	d:%0+4d\n", n2);
**	printf("- +	d:%-+4d\n", n1);
**	printf("- +	d:%-+4d\n\n", n2);
**
**	printf("sapce and single flag width 4\n");
**	printf("0 space	+d:%0 4d\n", n1);
**	printf("0 space	-d:%0 4d\n", n2);
**	printf("- space	+d:%- 4d\n", n1);
**	printf("- space	-d:%- 4d\n\n", n2);
**
**	printf("zero and single flag width 4\n");
**	printf("- 0	+d:%-04d\n", n1);
**	printf("- 0	-d:%-04d\n\n", n2);
**
**	printf("percision\n");
**	printf(".1 :%.1d\n", n1);
**	printf(".1 :%.1d\n", n2);
**	printf(".2 :%.2d\n", n1);
**	printf(".2 :%.2d\n", n2);
**	printf(".5 :%.5d\n", n1);
**	printf(".5 :%.5d\n\n", n2);
**
**	printf("width with zero flag and plus\n");
**	printf("1 :%+01d\n", n1);
**	printf("1 :%+01d\n", n2);
**	printf("3 :%+03d\n", n1);
**	printf("3 :%+03d\n", n2);
**	printf("10:%+010d\n", n1);
**	printf("10:%+010d\n", n2);
**	printf("-5:%+0-5d\n", n1);
**	printf("-5:%+0-5d\n\n", n2);
**
**	printf("width with zero flag and plus\n");
**	printf("01 :%+01d\n", n1);
**	printf("01 :%+01d\n", n2);
**	printf(" 1 :%+ 1d\n", n1);
**	printf(" 1 :%+ 1d\n", n2);
**	printf("03 :%+03d\n", n1);
**	printf("03 :%+03d\n", n2);
**	printf(" 3 :%+ 3d\n", n1);
**	printf(" 3 :%+ 3d\n", n2);
**	printf("010:%+010d\n", n1);
**	printf("010:%+010d\n", n2);
**	printf(" 10:%+ 10d\n", n1);
**	printf(" 10:%+ 10d\n", n2);
**	printf("5 :%+5d\n", n1);
**	printf("5 :%+5d\n\n", n2);
**	printf("5.8 :%+5.8d\n", n1);
**	printf("5.8 :%+5.8d\n", n2);
**	printf("5.4 :%+5.4d\n", n1);
**	printf("5.4 :%+5.4d\n\n", n2);
**	printf("10.8 :%+10.8d\n", n1);
**	printf("10.8 :%+10.8d\n", n2);
**	printf("10.4 :%+10.4d\n", n1);
**	printf("10.4 :%+10.4d\n\n", n2);
**	printf("   SP   :% d.\n", 60);
**	printf("   SP4w :% 4d.\n", 61);
**	printf("   .5   :%.5d.\n", 70);
**	printf("   4w   :%4d.\n", 80);
**	printf(" SP6w  +:%+ 6d.\n", 90);
**	printf("negSP   :% d.\n", -64);
**	printf("neg.5   :%.5d.\n", -74);
**	printf("neg4w   :%4d.\n", -84);
**	printf("neg6w  +:%+6d.\n\n", -94);
**	printf("   SP   :% d.\n", 1160);
**	printf("   .5   :%.5d.\n", 1170);
**	printf("   4w   :%4d.\n", 1180);
**	printf(" SP6w.7+:%+ 6.7d.\n", 1190);
**	printf("negSP   :% d.\n", -9164);
**	printf("neg.5   :%.5d.\n", -9174);
**	printf("neg4w   :%4d.\n", -9184);
**	printf("neg6w.7+:%+6.7d.\n", -9194);
**	printf("10w plus space:% +10d\n", n1);
**	printf("10w plus space:% +10d\n", n2);
**	printf("10w space     :% 10d\n", n1);
**	printf("10w space     :% 10d\n\n", n2);
**
**	printf("percision and width of 8\n");
**	printf(".1 :%8.1d\n", n1);
**	printf(".1 :%8.1d\n", n2);
**	printf(".2 :%8.2d\n", n1);
**	printf(".2 :%8.2d\n", n2);
**	printf(".5 :%8.5d\n", n1);
**	printf(".5 :%8.5d\n\n", n2);
**	printf("percision and width of 4\n");
**	printf(".1 :%4.1d\n", n1);
**	printf(".1 :%4.1d\n", n2);
**	printf(".2 :%4.2d\n", n1);
**	printf(".2 :%4.2d\n", n2);
**	printf(".5 :%4.5d\n", n1);
**	printf(".5 :%4.5d\n\n", n2);
**	printf("percision and width of 2\n");
**	printf(".1 :%2.1d\n", n1);
**	printf(".1 :%2.1d\n", n2);
**	printf(".2 :%2.2d\n", n1);
**	printf(".2 :%2.2d\n", n2);
**	printf(".5 :%2.5d\n", n1);
**	printf(".5 :%2.5d\n\n", n2);
**	printf("percision 7 and width of ?\n");
**	printf(".7    :%0 .7d\n", n1);
**	printf(".7    :%0 .7d\n", n2);
**	printf(".7 10w:%0 10.7d\n", n1);
**	printf(".7 10w:%0 10.7d\n", n2);
**	printf(".7 4w :%0 4.7d\n", n1);
**	printf(".7 4w :%0 4.7d\n\n", n2);
**
**	printf("-            :%-d.\n", n1);
**	printf("-            :%-d.\n", n2);
**	printf("- space      :%- d.\n", n1);
**	printf("- space      :%- d.\n", n2);
**	printf("-+space      :%-+ d.\n", n1);
**	printf("-+space      :%-+ d.\n", n2);
**	printf("1w-          :%-1d.\n", n1);
**	printf("1w-          :%-1d.\n", n2);
**	printf("1w- space    :%- 1d.\n", n1);
**	printf("1w- space    :%- 1d.\n", n2);
**	printf("1w-+space    :%-+ 1d.\n", n1);
**	printf("1w-+space    :%-+ 1d.\n", n2);
**	printf("5w-          :%-5d.\n", n1);
**	printf("5w-          :%-5d.\n", n2);
**	printf("5w- space    :%- 5d.\n", n1);
**	printf("5w- space    :%- 5d.\n", n2);
**	printf("5w-+space    :%-+ 5d.\n", n1);
**	printf("5w-+space    :%-+ 5d.\n", n2);
**	printf("10w-         :%-10d.\n", n1);
**	printf("10w-         :%-10d.\n", n2);
**	printf("10w- space   :%- 10d.\n", n1);
**	printf("10w- space   :%- 10d.\n", n2);
**	printf("10w-+space   :%-+ 10d.\n", n1);
**	printf("10w-+space   :%-+ 10d.\n\n", n2);
**
**	printf("-         .2 :%-.2d.\n", n1);
**	printf("-         .2 :%-.2d.\n", n2);
**	printf("- space   .2 :%- .2d.\n", n1);
**	printf("- space   .2 :%- .2d.\n", n2);
**	printf("-+space   .2 :%-+ .2d.\n", n1);
**	printf("-+space   .2 :%-+ .2d.\n", n2);
**	printf("1w-       .2 :%-1.2d.\n", n1);
**	printf("1w-       .2 :%-1.2d.\n", n2);
**	printf("1w- space .2 :%- 1.2d.\n", n1);
**	printf("1w- space .2 :%- 1.2d.\n", n2);
**	printf("1w-+space .2 :%-+ 1.2d.\n", n1);
**	printf("1w-+space .2 :%-+ 1.2d.\n", n2);
**	printf("5w-       .2 :%-5.2d.\n", n1);
**	printf("5w-       .2 :%-5.2d.\n", n2);
**	printf("5w- space .2 :%- 5.2d.\n", n1);
**	printf("5w- space .2 :%- 5.2d.\n", n2);
**	printf("5w-+space .2 :%-+ 5.2d.\n", n1);
**	printf("5w-+space .2 :%-+ 5.2d.\n", n2);
**	printf("10w-      .2 :%-10.2d.\n", n1);
**	printf("10w-      .2 :%-10.2d.\n", n2);
**	printf("10w- space.2 :%- 10.2d.\n", n1);
**	printf("10w- space.2 :%- 10.2d.\n", n2);
**	printf("10w-+space.2 :%-+ 10.2d.\n", n1);
**	printf("10w-+space.2 :%-+ 10.2d.\n\n", n2);
**
**	printf("-         .6 :%-.6d.\n", n1);
**	printf("-         .6 :%-.6d.\n", n2);
**	printf("- space   .6 :%- .6d.\n", n1);
**	printf("- space   .6 :%- .6d.\n", n2);
**	printf("-+space   .6 :%-+ .6d.\n", n1);
**	printf("-+space   .6 :%-+ .6d.\n", n2);
**	printf("1w-       .6 :%-1.6d.\n", n1);
**	printf("1w-       .6 :%-1.6d.\n", n2);
**	printf("1w- space .6 :%- 1.6d.\n", n1);
**	printf("1w- space .6 :%- 1.6d.\n", n2);
**	printf("1w-+space .6 :%-+ 1.6d.\n", n1);
**	printf("1w-+space .6 :%-+ 1.6d.\n", n2);
**	printf("5w-       .6 :%-5.6d.\n", n1);
**	printf("5w-       .6 :%-5.6d.\n", n2);
**	printf("5w- space .6 :%- 5.6d.\n", n1);
**	printf("5w- space .6 :%- 5.6d.\n", n2);
**	printf("5w-+space .6 :%-+ 5.6d.\n", n1);
**	printf("5w-+space .6 :%-+ 5.6d.\n", n2);
**	printf("10w-      .6 :%-10.6d.\n", n1);
**	printf("10w-      .6 :%-10.6d.\n", n2);
**	printf("10w- space.6 :%- 10.6d.\n", n1);
**	printf("10w- space.6 :%- 10.6d.\n", n2);
**	printf("10w-+space.6 :%-+ 10.6d.\n", n1);
**	printf("10w-+space.6 :%-+ 10.6d.\n\n", n2);
**
**	printf(".4         :%-.8d.\n", n1);
**	printf(".4         :%-.8d.\n", n2);
**
**	printf(".5         :%.5d.\n", n1);
**	printf(".5         :%.5d.\n", n2);
**	printf(".5space    :% .5d.\n", n1);
**	printf(".5space    :% .5d.\n", n2);
**	printf(".5space+   :% +.5d.\n", n1);
**	printf(".5space+   :% +.5d.\n", n2);
**	printf(".5zero     :%0.5d.\n", n1);
**	printf(".5zero     :%0.5d.\n", n2);
**	printf(".5zeroSP   :% 0.5d.\n", n1);
**	printf(".5zeroSP   :% 0.5d.\n", n2);
**	printf("5w.5space  :% 5.5d.\n", n1);
**	printf("5w.5space  :% 5.5d.\n", n2);
**	printf("5w.5space+ :% +5.5d.\n", n1);
**	printf("5w.5space+ :% +5.5d.\n", n2);
**	printf("5w.5zero   :%05.5d.\n", n1);
**	printf("5w.5zero   :%05.5d.\n", n2);
**	printf("5w.5zeroSP :%0 5.5d.\n", n1);
**	printf("5w.5zeroSP :% 05.5d.\n", n2);
**	printf("10w.5space :% 10.5d.\n", n1);
**	printf("10w.5space :% 10.5d.\n", n2);
**	printf("10w.5space+:% +10.5d.\n", n1);
**	printf("10w.5space+:% +10.5d.\n", n2);
**	printf("10w.5zero  :%010.5d.\n", n1);
**	printf("10w.5zero  :%010.5d.\n", n2);
**	printf("10w.5zeroSP:%0 10.5d.\n", n1);
**	printf("10w.5zeroSP:%0 10.5d.\n", n2);
**	printf("%d\n", n1);
**	printf("%d\n", n2);
**	printf("%d\n", n1);
**	printf("%d\n", n2);
**	printf("%d\n", n1);
**	printf("%d\n", n2);
**	printf("%d\n", n1);
**	printf("%d\n", n2);
**	printf("%5%\n");
**	printf("%05%\n");
**
**	printf(".% s..", "string test.\n");
**	printf(".%        s..", "test.\n");
**	printf("%+s", "test.\n");
**	printf("%-05c.\n%0.5c.\n\n", 'a', 'b');
**	printf("%-05s.\n%0.5s.\n%-05.5s.\n\n", "abc", "abc", "abc");
**	printf("%-05s.\n%0.5s.\n%-05.5s.\n\n", "abcdef", "abcdef", "abcdef");
**	printf("%-010s.\n%0.5s.\n%-010.5s.\n\n", "aXcdef", "aXcdef", "aXcdef");
**	printf("%-05s.\n%0.10s.\n%-05.10s.\n\n", "aXYcdef", "aXYcdef", "aXYcdef");
**
**	printf(".%-10.5s.\n", "123456");
**	printf(".%-6.5s.\n\n\n", "123456");
**
**	char	c;
**	int		i;
**	char	*s;
**	c = 'X';
**	s = "%%c test :%c.\n";
**	i = ft_printf("regular string test\n");
**
**
**
**	n1 = 400;
**	n2 = -400;
**
**
**	ft_printf("%%c test :%c.\n", c);
**	printf("%%c test :%c. <<\n\n", c);
**	ft_printf("%%%% test :%%.\n");
**	printf("%%%% test :%%. <<\n\n");
**	ft_printf("%%d test :% .2d.\n", -20);
**	printf("%%d test :% .2d. <<\n\n", -20);
**	ft_printf("%%d test :%.3d.\n", -21);
**	printf("%%d test :%.3d. <<\n\n", -21);
**	ft_printf("%%d test :% .4d.\n", -22);
**	printf("%%d test :% .4d. <<\n\n", -22);
**	ft_printf("%%d test :%+.2d.\n", 23);
**	printf("%%d test :%+.2d. <<\n\n", 23);
**	ft_printf("%%d test :%.3d.\n", 24);
**	printf("%%d test :%.3d. <<\n\n", 24);
**	ft_printf("%%d test :%+.4d.\n", 25);
**	printf("%%d test :%+.4d. <<\n\n", 25);
**	ft_printf("%%d test :%2d.\n", -26);
**	printf("%%d test :%2d. <<\n\n", -26);
**	ft_printf("%%d test :%10.4d.\n", -27);
**	printf("%%d test :%10.4d. <<\n\n", -27);
**	ft_printf("%%d test :%4.5d.\n", -28);
**	printf("%%d test :%4.5d. <<\n\n", -28);
**	ft_printf("%%d test :%+2d.\n", 29);
**	printf("%%d test :%+2d. <<\n\n", 29);
**	ft_printf("%%d test :%3d.\n", 30);
**	printf("%%d test :%3d. <<\n\n", 30);
**	ft_printf("%%d test :%+4d.\n", -31);
**	printf("%%d test :%+4d. <<\n\n", -31);
**	ft_printf(".5         :%.5d.\n", n1);
**	ft_printf(".5         :%.5d.\n", n2);
**	ft_printf(".5space    :% .5d.\n", n1);
**	ft_printf(".5space    :% .5d.\n", n2);
**	ft_printf(".5space+   :% +.5d.\n", n1);
**	ft_printf(".5space+   :% +.5d.\n", n2);
**	ft_printf(".5zero     :%0.5d.\n", n1);
**	ft_printf(".5zero     :%0.5d.\n", n2);
**	ft_printf(".5zeroSP   :% 0.5d.\n", n1);
**	ft_printf(".5zeroSP   :% 0.5d.\n", n2);
**	ft_printf("5w.5space  :% 5.5d.\n", n1);
**	ft_printf("5w.5space  :% 5.5d.\n", n2);
**	ft_printf("5w.5space+ :% +5.5d.\n", n1);
**	ft_printf("5w.5space+ :% +5.5d.\n", n2);
**	ft_printf("5w.5zero   :%05.5d.\n", n1);
**	ft_printf("5w.5zero   :%05.5d.\n", n2);
**	ft_printf("5w.5zeroSP :%0 5.5d.\n", n1);
**	ft_printf("5w.5zeroSP :% 05.5d.\n", n2);
**	ft_printf("10w.5space :% 10.5d.\n", n1);
**	ft_printf("10w.5space :% 10.5d.\n", n2);
**	ft_printf("10w.5space+:% +10.5d.<<\n", n1);
**	ft_printf("10w.5space+:% +10.5d.<<\n", n2);
**	ft_printf("10w.5zero  :%010.5d.<<\n", n1);
**	ft_printf("10w.5zero  :%010.5d.\n", n2);
**	ft_printf("10w.5zeroSP:%0 10.5d.\n", n1);
**	ft_printf("10w.5zeroSP:%0 10.5d.\n", n2);
**	ft_printf("%10s is a string\n\n", NULL);
**	ft_printf("% 10.5d\n", 4242);
**	ft_printf("%+10.5d\n", 4242);
**	ft_printf("%03.2d\n", -1);
**	ft_printf("%.d. %.0d\n", 0, 0);
**	printf("%d. %d\n", 0, 0);
**	ft_printf("%5.d %5.0d\n", 0, 0);
**	printf("%5.d %5.0d\n", 0, 0);
**	ft_printf("%+d", 0);
**	i = ft_printf("%05d", 42);
**	ft_printf("%0+5d\n", 42);
**	i = ft_printf("%05d", -42);
**	ft_printf("%0+5d\n", -42);
**
**	ft_printf("%10.5d\n", -216);
**	printf("%10.5d\n", -216);
**	printf(".\n\nbytes: %d\n", i);
**	i = ft_printf("%10.5i", -216);
**	i = ft_printf("%0+5d", 42);
**
**	ft_printf("\"");
**	i = ft_printf("% 05d", 43);
**	ft_printf("\"");
**	ft_printf(" <- ft_printf.bytes -> %d\n", i);
**	printf("\"");
**	i = printf("% 05d", 43);
**	printf("\"");
**	printf(" <-    printf.bytes -> %d\n\n", i);
**
**	ft_printf("\"");
**	i = ft_printf("% 03d", 0);
**	ft_printf("\"");
**	ft_printf("   <- ft_printf.bytes -> %d\n", i);
**	printf("\"");
**	i = printf("% 03d", 0);
**	printf("\"");
**	printf("   <-    printf.bytes -> %d\n\n", i);
*/
